dbconf:
    # 数据库类型 mysql, sqlite3, postgres, sqlserver
    driver: mysql
    # 服务器地址 本地建议 127.0.0.1
    hostname: 127.0.0.1
    # 端口 默认3306
    hostport: 3306
    # 用户名
    username: root
    # 密码
    password: "123456"
    # 数据库名
    database: gozero_base
    # 数据表前缀
    prefix: 
log:
    # 日志等级debug
    level: info  
    # 日志根目录
    root_dir: ./ 
    # 日志文件名称
    filename: app.log 
    # 写入格式 可选json
    format: json 
    # 是否显示调用行
    show_line: true
    # 旧文件的最大个数 
    max_backups: 3 
    # 日志文件最大大小（MB）
    max_size: 500 
    # 旧文件的最大保留天数
    max_age: 28
    # 是否压缩 
    compress: true 